name: rougecombien
up:
  - homebrew:
    - golangci/tap/golangci-lint
  - go:
      version: 1.13
      modules: true
  - railgun
  - custom:
      name: Build command line tools
      met?: test -f "bin/rougecombien"
      meet: go build -o bin/rougecombien cmd/rougecombien/main.go
  - custom:
      name: Load dependencies
      met?: go mod tidy
      meet: go mod tidy
server:
  run: go run -race ./cmd/rougecombien dev
commands:
  build: go build -o bin/rougecombien cmd/rougecombien/main.go
  lint: golangci-lint run